repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-xml
      - id: check-toml
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python 3.9
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        additional_dependencies:
          - isort[pyproject]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: '3.8.3'
  #   hooks:
  #     - id: flake8
  #       args: [--config=.flake8]
  #       additional_dependencies:
  #         - flake8-debugger
  #         - flake8-deprecated
  #         - flake8-mutable
  #         - flake8-plone-api
  #         - flake8-plone-hasattr
  #         - flake8-print
  #         - flake8-quotes
  #         - flake8-string-format
  #         - pep8-naming
